version: "3.9"

services:
  db:
    image: postgres:16
    container_name: moodle-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  php:
    build:
      context: ./php
      args:
        PHP_VERSION: "8.2" 
    container_name: moodle-php
    restart: unless-stopped
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_MEMORY_LIMIT: "512M"
      PHP_MAX_UPLOAD: "200M"
      PHP_MAX_EXECUTION_TIME: "300"
    volumes:
      - ./moodle:/var/www/moodle   # put Moodle code here
      - moodledata:/var/www/moodledata
      - ./php/conf.d/moodle.ini:/usr/local/etc/php/conf.d/moodle.ini:ro # custom PHP settings
      - ./php/conf.d/m_www.comf:/usr/local/etc/php/conf.d/m_www.conf:ro # custom PHP settings
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:stable
    container_name: moodle-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/moodle:ro
      - moodledata:/var/www/moodledata:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started

volumes:
  dbdata:
  moodledata:
