services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-moodle}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-moodle}"]
      interval: 10s
      timeout: 5s
      retries: 10

  php:
    build:
      context: ./php
      args: { PHP_VERSION: "8.2" }
    image: moodle-php:latest
    restart: unless-stopped
    volumes:
      - ./moodle:/var/www/moodle              # <— one mount, both sites
      - moodledata_mobi:/var/moodledata/mobi  # per-site dataroots
      - moodledata_cu:/var/moodledata/cu
      - ./php/conf.d/moodle.ini:/usr/local/etc/php/conf.d/moodle.ini:ro

  web:
    image: nginx:stable
    ports: ["80:80"]
    depends_on: { php: { condition: service_started } }
    volumes:
      - ./moodle:/var/www/moodle:ro           # code only (RO)
      - ./nginx/mobi.conf:/etc/nginx/conf.d/10-mobi.conf:ro
      - ./nginx/cu.conf:/etc/nginx/conf.d/20-cu.conf:ro

  cron-mobi:
    image: moodle-php:latest
    volumes:
      - ./moodle:/var/www/moodle
      - ./moodledata/mobi:/var/moodledata/mobi
    entrypoint: >
      sh -c "while true; do
              php /var/www/moodle/mobi/admin/cli/cron.php || true;
              sleep 60;
            done"

  cron-cu:
    image: moodle-php:latest
    volumes:
      - ./moodle:/var/www/moodle
      - ./moodledata/cu:/var/moodledata/cu
    entrypoint: >
      sh -c "while true; do
              php /var/www/moodle/cu/admin/cli/cron.php || true;
              sleep 60;
            done"

volumes:
  dbdata:
  moodledata_mobi:
  moodledata_cu:
